# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.

[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.123.8"
  GO_VERSION = "1.22.1"
  NODE_VERSION = "22.13.1"
  HUGO_THEME = "repo"
